version: "3"

services:
  elasticsearch:
    # image: elasticsearch
    container_name: elasticsearch
    build: ./elasticsearch
    ports:
      - "9200:9200"
    privileged: true
    networks: 
      - default
# networks: 
#   default:
#     external: 
#       name: mysql_default